### PR TITLE
snap: update to core24

### PR DESCRIPTION
**Pull request by jssotomdz**
this pull request migrates the app center to core24
migration seems very straightforward only requiring the change in the base parameter and adding git as build parameter (how did it get it before by the way?)

### CODE REVIEW

**Comment by d-loose** [comment]
> this pull request migrates the app center to core24 migration seems very straightforward only requiring the change in the base parameter and adding git as build parameter (how did it get it before by the way?)

Hm interesting, it wasn't needed for core22, I don't know why though. Maybe @kenvandine knows

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Comment by kenvandine** [comment]
> > this pull request migrates the app center to core24 migration seems very straightforward only requiring the change in the base parameter and adding git as build parameter (how did it get it before by the way?)
> 
> Hm interesting, it wasn't needed for core22, I don't know why though. Maybe @kenvandine knows

Sounds like a snapcraft bug.  Snapcraft included git as a build-package when sources came from git automatically.

**Comment by d-loose** [comment]
> Sounds like a snapcraft bug. Snapcraft included git as a build-package when sources came from git automatically.

The source-type isn't set here, so maybe something changed in the detection mechanism?

**Comment by MrSIHAB** [comment]
> > this pull request migrates the app center to core24 migration seems very straightforward only requiring the change in the base parameter and adding git as build parameter (how did it get it before by the way?)
> 
> Hm interesting, it wasn't needed for core22, I don't know why though. Maybe @kenvandine knows

actually it was built on ubuntu 22.04 and probably core 24 hadn't that much dependency or plugin then.

**Pull request merged**
