### PR TITLE
Add the app name in Polish

### PR DESCRIPTION
**Pull request by Matthaiks**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
LGTM! (Except the CLA.)

**Comment by AsciiWolf** [comment]
@Matthaiks Any chance you could [sign](https://ubuntu.com/legal/contributors/agreement) the CLA?

**Comment by Matthaiks** [comment]
@AsciiWolf I'm not interested in that.

**Comment by AsciiWolf** [comment]
@d-loose Any chance someone else could add the Polish (and [Slovak](https://github.com/ubuntu/app-center/pull/1458)) app names into the desktop file?

**Pull request closed without merging**
