### PR TITLE
docs: Change `Github` to `GitHub`

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by spydon** [comment]
@jbampton if you sign the CLA I can merge this, otherwise I'll close it and fix up the typo separately. :)

**Comment by jbampton** [comment]
Hey @spydon  I have signed the agreement with my email `jbampton@gmail.com`  but the CLA still fails

**Comment by spydon** [comment]
> Hey @spydon  I have signed the agreement with my email `jbampton@gmail.com`  but the CLA still fails

Ah, I think the commits aren't connected to that email?

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git

**Comment by jbampton** [comment]
I'm using the GitHub-provided noreply email address on GitHub

**Comment by spydon** [comment]
> I'm using the GitHub-provided noreply email address on GitHub

Yeah, you have to change the e-mail of the commit to the one that you signed the cla with.

This should be enough:
```
git commit --amend --author="author_name <email>" --no-edit
git push -f
```

**Comment by spydon** [comment]
> - jbampton@gmail.com ✕ (has no Launchpad account)

You don't seem to have a launchpad account connected to that email?

**Comment by jbampton** [comment]
https://launchpad.net/~johnbam

Seems it is not picking up the account

**Comment by jbampton** [comment]
Thank you @spydon  well done :100:

**Pull request merged**
