### PR TITLE
fix: Remove secondary action icons

### PR DESCRIPTION
**Pull request by spydon**
image

image

### CODE REVIEW

**Comment by anasereijo** [comment]
The padding seems to be quite different in both dropdowns. The one on the app page seems to be wider than the one on manage. can this be matched?

**Comment by spydon** [comment]
> The padding seems to be quite different in both dropdowns. The one on the app page seems to be wider than the one on manage. can this be matched?

Yup, that is something we have discussed before, we have #1775 open for that. :)

**Comment by anasereijo** [comment]
LGTM then!

**Comment by spydon** [comment]
> LGTM then!

If you put it as a review I can merge it 😉

**Review by d-loose — APPROVED** [review]

**Pull request merged**
