### PR TITLE
Swedish entry in app-center.desktop

### PR DESCRIPTION
**Pull request by gunnarhj**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@gunnarhj I think your accidentally based your branch on top of a wrong branch. Eventually close this PR and open a new one freshly based

**Comment by gunnarhj** [comment]
@Feichtmeier: I have changed the base branch from dev to main. Hopefully that's what you asked for.

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Comment by d-loose** [comment]
@tim-hm Branch protection rules currently enforce signed commits - do we expect that for community contributions as well?

**Pull request merged**
