### PR TITLE
fix(manage page): button content alignment is not consistent

### LINKED ISSUE #1558: Manage page: button content aligment is not consistent
grafik

In the top control panel with the "update all button" the button height is correct and thus the content padding matches and thus the content is positioned in the middle.
However in those containers with the border, it looks like the button height is a little bit squeezed and thus the content padding is too much for the content and thus the content is positioned a little bit too much down
May be an optical illusion but I am almost certain :crossed_fingers:

### PR DESCRIPTION
**Pull request by shreyasSarve**
fix: Manage page: button content aligment is not consistent
Screenshot from 2024-01-10 17-12-27

fix #1558

### CODE REVIEW

**Comment by BLKKKBVSIK** [comment]
Great work ! 
You will have to sign the CLA so we can merge your PR.

**Comment by shreyasSarve** [comment]
i have signed it but i dont to know why this failling

**Comment by shreyasSarve** [comment]
@BLKKKBVSIK  i have signed it now you can approve my pull request

**Comment by shreyasSarve** [comment]
@BLKKKBVSIK Can you approve awaiting workflows to check for failled test

**Comment by BLKKKBVSIK** [comment]
Sorry for the late reply.
I've done the re-run :)

**Pull request closed without merging**
