### PR TITLE
feat: Installing section for manage page

### PR DESCRIPTION
**Pull request by spydon**
[Screencast from 2024-09-10 18-17-37.webm](https://github.com/user-attachments/assets/715e6407-3b75-441b-bae9-ab5063f61a25)

This also contains some small fixes for buttons and spacing + consolidates the code for the "button bars".

### CODE REVIEW

**Comment by anasereijo** [comment]
whoop whooppp 🙌 

the only thing missing is the cancel button: 

Screenshot 2024-09-06 at 09 54 32

**Review by d-loose — APPROVED** [review]
Unrelated to this PR, I noticed that there's also some space missing between the 'Install' and 'Cancel' buttons on the app page.

On this PR: looks great and works well! Feel free to merge it after adding the cancel button Ana requested :)

**Comment by anasereijo** [comment]
> Unrelated to this PR, I noticed that there's also some space missing between the 'Install' and 'Cancel' buttons on the app page.

@d-loose great catch! you can officially become a designer now ;) haha

**Comment by spydon** [comment]
> whoop whooppp 🙌
> 
> the only thing missing is the cancel button:
> Screenshot 2024-09-06 at 09 54 32

@anasereijo Ah right, should the update list also have a cancel button? It doesn't in Figma, and maybe it's unnecessary, like who cancels and update that they've started... Just checking if the button bars should be the same across the lists.

[Screencast from 2024-09-06 11-31-12.webm](https://github.com/user-attachments/assets/0644e2e0-e84f-4ccd-8456-6c8a72d67903)

**Comment by anasereijo** [comment]
Looks goooood 🥇

**Review by anasereijo — APPROVED** [review]

**Review by d-loose — APPROVED** [review]

**Pull request merged**
