### PR TITLE
Track active changes in the application and show list in manage page.

### PR DESCRIPTION
**Pull request by codinesh**
Fixes https://github.com/ubuntu/app-center/issues/1438, by displaying a section for installing/uninstalling snaps.

image

To Listen to the changes from Snap details page, tapped on to SnapModel._activeChangeListener to know the installs, uninstalls and change updates. This will call the ManageModel to maintain the list of active snaps.
Scope of this change to track the changes made from this app, as a workaround to [an issue in /v2/changes](https://forum.snapcraft.io/t/how-to-find-the-impacted-snap-from-the-get-v2-changes-rest-api/37965) api, which doesn't give enough information to identify corresponding snap from the response.

Workaround is discussed https://github.com/ubuntu/app-center/issues/1438#issuecomment-1833651474.

Here is link to accidentally closed [original PR](https://github.com/ubuntu/app-center/pull/1517#issue-2030000382) with some discussions. Current PR is created with code changes from original PR.

### CODE REVIEW

**Comment by codinesh** [comment]
Requesting @d-loose, @BLKKKBVSIK and @anasereijo to review this PR instead of #1517.

Thanks for understanding.

**Comment by BLKKKBVSIK** [comment]
LGTM !
Let's just wait until @anasereijo comes back from holidays to see if the UI changes are approuved :)

**Comment by codinesh** [comment]
Sounds good, thanks.

**Comment by anasereijo** [comment]
Great work @codinesh! Just a few points:

- when there are no apps being installed, this section will be hidden, correct?
- would be nice to display the option to cancel the installation
- maybe we can remove the more options button [ ... ] since it's probably not very useful or no actions to be taken while the installation is in progress

did a quick mock-up of how it could look like:

Screenshot 2024-01-02 at 16 03 20

**Comment by codinesh** [comment]
> Great work @codinesh! Just a few points:
> 
> - when there are no apps being installed, this section will be hidden, correct?

Yes, that is the behavior..


Thanks for suggestions on additional options and the Cancel button, will take up these changes. 

Will match figma. Thank you.

**Comment by codinesh** [comment]
Hello @anasereijo, 

> maybe we can remove the more options button [ ... ] since it's probably not very useful or no actions to be taken while the installation is in progress

Should we keep the [...] options button to make it consistent with other two sections. Please see the screenshot. Since the item is to open, will be navigated to snap detail page. 

Please let me know what you thing, change is simple in any case.

Screenshot from 2024-01-03 19-42-23

Thank you

**Comment by codinesh** [comment]
> Hello @anasereijo,
> 
> > maybe we can remove the more options button [ ... ] since it's probably not very useful or no actions to be taken while the installation is in progress
> 
> Should we keep the [...] options button to make it consistent with other two sections. Please see the screenshot. Since the item is to open, will be navigated to snap detail page.
> 
> Please let me know what you thing, change is simple in any case.
> 
> Screenshot from 2024-01-03 19-42-23
> 
> Thank you

Hi @anasereijo please have a look at this comment and share your opinion.

**Comment by anasereijo** [comment]
Hi @codinesh, apologies for my late reply.

Good catch! we should keep consistency with the other sections indeed. so lets keep the button [ ... ] whilst the snap is installing.

thank you!

**Comment by spydon** [comment]
Thanks a lot for you hard work @codinesh! I think it helped a lot in bringing forward the final design of this. <3
I'll close it since it's been superseded by #1810.

**Pull request closed without merging**
