### PR TITLE
fix: Height of search fields should be static

### PR DESCRIPTION
**Pull request by spydon**
[Screencast from 2024-10-04 16-31-39.webm](https://github.com/user-attachments/assets/85998e6a-e416-46af-a10a-7d745a5e9f0d)

Fixes: #1832

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Lgtm
I think it's also used in the manage page does the height still fit now?

**Comment by spydon** [comment]
> Lgtm I think it's also used in the manage page does the height still fit now?

That's why I showed the manage page search bar in the video too :smile:

**Comment by anasereijo** [comment]
maybe it's the video recording, but the focused outline (orange) isn't rendering well?

Screenshot 2024-10-04 at 15 48 36

**Comment by spydon** [comment]
> maybe it's the video recording, but the focused outline (orange) isn't rendering well?
> Screenshot 2024-10-04 at 15 48 36

It's just the video, no idea why it became such low quality when I uploaded it here.

**Review by anasereijo — APPROVED** [review]

**Comment by anasereijo** [comment]
Hmmm I approved the changes but didn't look at the code! 😄

**Comment by Feichtmeier** [comment]
> > Lgtm I think it's also used in the manage page does the height still fit now?
> 
> That's why I showed the manage page search bar in the video too :smile: 

Woops ... Right 👍 sorry

**Review by d-loose — APPROVED** [review]

**Pull request merged**
