### PR TITLE
fix: Move featured section to top of explore page

### PR DESCRIPTION
**Pull request by spydon**
image

UDENG-3749

### CODE REVIEW

**Review by d-loose — APPROVED** [review]
:+1:

UDENG-3749

**Comment by spydon** [comment]
> 👍

I'm adding the arts category too, but I guess it would actually cleaner to do that in a separate PR, so I'll merge this.

**Comment by anasereijo** [comment]
can we have the following gradient as a background? I had a look at the page and the colours of banners and changed a few. These gradients should exist somewhere, I believe. 

Screenshot 2024-08-28 at 15 50 51

**Comment by spydon** [comment]
> can we have the following gradient as a background? I had a look at the page and the colours of banners and changed a few. These gradients should exist somewhere, I believe.
> Screenshot 2024-08-28 at 15 50 51

I opened a new issue for that!

**Pull request merged**
