### PR TITLE
[store_page]: change the button icons based on `selected`

### PR DESCRIPTION
**Pull request by soumyaDghosh**
[Screencast from 2023-12-18 20-39-29.webm](https://github.com/ubuntu/app-center/assets/72045785/df49e95f-8911-40ad-b209-f54efaa876e3)

### CODE REVIEW

**Comment by BLKKKBVSIK** [comment]
Great work! 
We need to see with @anasereijo if this is the UX we want.
She's currently on leave, so the PR will be merged later on if everything is OK 👍

**Comment by anasereijo** [comment]
That's great @soumyaDghosh! 
Could you update the wrench icon as well? On your screen recording, it's always filled. Thanks!

**Comment by soumyaDghosh** [comment]
The wrench icon doesn't have a outlined icon in the current release of `yaru_icons` yet. So, it can't be helped. We'll have to wait for the next release.

**Comment by anasereijo** [comment]
> The wrench icon doesn't have a outlined icon in the current release of `yaru_icons` yet. So, it can't be helped. We'll have to wait for the next release.

I believe Paul @Jupi007 worked on it recently. Am I right, Paul?

**Comment by Jupi007** [comment]
@anasereijo Yes, and I just released it: https://github.com/ubuntu/yaru_icons.dart/releases/tag/v2.3.0 😉

Here is the related PR btw: https://github.com/ubuntu/yaru_icons.dart/pull/190

**Comment by soumyaDghosh** [comment]
@anasereijo @Jupi007 done!

**Review by BLKKKBVSIK — APPROVED** [review]

**Pull request merged**
