### PR TITLE
feat: add custom error view

### PR DESCRIPTION
**Pull request by d-loose**
@anasereijo we can go over design and copy for all of those next week:

Error message when refreshing a single snap or switching the channel while it is running:
Screenshot from 2024-06-27 15-41-46

Generic error page with custom message for `SnapdException(kind: 'network-timeout')` (see #1479 and #1668)
Screenshot from 2024-06-28 17-01-26

Generic error page with custom message for `SnapdException(message: 'too many requests')` (see #1684)
Screenshot from 2024-06-28 17-00-44

Ref #1479, #1668, #1684

UDENG-3056
UDENG-3264

### CODE REVIEW

**Comment by d-loose** [comment]
Updated error pages matching the Figma designs:

Network error:
Screenshot from 2024-07-10 16-09-26

Server error (e.g. 'too many requests')
Screenshot from 2024-07-10 16-08-01

Unknown error:
Screenshot from 2024-07-10 16-07-44

'Retry' will retry the action prior to encountering the error (loading search results, displaying a snap page, ..). 'Check status' will open https://status.snapcraft.io/ in a browser.

**Review by spydon — APPROVED** [review]
Lgtm functionality-wise!
I'm sure Ana will want to have a say in the design for the generic ones later. 😄

**Comment by d-loose** [comment]
> I'm sure Ana will want to have a say in the design for the generic ones later. 😄

I've double-checked Figma now and realized that I forgot to actually include the action texts for each error in the view. Added them now and updated the screenshots in my previous comment!

**Comment by Feichtmeier** [comment]
Imho a centered, vertical layout could be better, especially for when the window size varies

 Image
   Text 
Buttons

**Comment by spydon** [comment]
> Imho a centered, vertical layout could be better, especially for when the window size varies
> 
> ```
>  Image
>   Text 
> Buttons
> ```

I agree, it feels a bit "off" now, let's check that with Ana :)

**Comment by madsrh** [comment]
> Imho a centered, vertical layout could be better, especially for when the window size varies

+1 for centered layout 👍 

> I've double-checked Figma now... 

Obviously, us mortals can't see the Figma mockups, but shouldn't the "headline" have a different styling? I know that it is slightly larger, but it's barely visible and doesn't feel like a propper heading. Maybe just use the same weight as we use on the [Update page](https://private-user-images.githubusercontent.com/31812582/325912976-fcac94eb-ab52-4fc7-a8b0-0a5153e4632c.png)?

image

**Comment by anasereijo** [comment]
It does indeed look better centered 👍 
The heading looks almost the same as the text, so if that can be changed, go for it. 

The spacing between elements looks odd - the first line of text looks closer to the heading than to the second line of text. I suggest adding more padding between the heading and the text, and decrease (or remove) the padding between the two lines of text.

**Comment by d-loose** [comment]
Column layout with adjusted spacing and font size:

Screenshot from 2024-07-11 11-46-13
Screenshot from 2024-07-11 11-45-49
Screenshot from 2024-07-11 11-44-31

**Review by anasereijo — APPROVED** [review]

**Pull request merged**
