### PR TITLE
feat: adding shimmer when the ratings are loading.

### LINKED ISSUE #1447: Widgets on the snap page move around during initialization
When the ratings backend responds, the voting data is dynamically added to the snap page. However, the transition is far from smooth (added an artificial delay to emphasize the issue):

[Screencast from 2023-10-06 17-44-12.webm](https://github.com/ubuntu/app-center/assets/113362648/8c8e50f2-9f07-4848-8421-46aa4698a1d2)

We could either display a placeholder with a loading and error state, or move the ratings information to a different spot on the page, where it doesn't disrupt other elements.

### PR DESCRIPTION
**Pull request by BLKKKBVSIK**
In this PR:

- Adding shimmers placeholder text during the loading of the ratings.

fix #1447

[Screencast from 2023-12-12 11-54-14.webm](https://github.com/ubuntu/app-center/assets/20175372/6d7ee919-6cde-4d8f-b055-df909c400d64)

### CODE REVIEW

**Comment by anasereijo** [comment]
Could we just have the whole page loading using a [skeleton loader](https://m3.material.io/styles/motion/transitions/transition-patterns#f7ff608a-087d-4a4e-9e83-f1af69184487)?

**Comment by BLKKKBVSIK** [comment]
> Could we just have the whole page loading using a [skeleton loader](https://m3.material.io/styles/motion/transitions/transition-patterns#f7ff608a-087d-4a4e-9e83-f1af69184487)?

Except for the ratings, there is nothing that needs loading on the package page.

**Comment by anasereijo** [comment]
@BLKKKBVSIK, I think it looks odd using the skeleton (shimmer) just on the ratings, as it's only loading a tiny fraction of the screen. 
I think we should force the whole section to be skeleton until everything in there is ready to be loaded (in this case, ratings). 
It's more perceptive that it's loading information, and the order we want users to read the content is kept (ratings first)

Screenshot 2023-12-13 at 14 29 28

**Comment by d-loose** [comment]
However, all the other information is available immediately and doesn't need any loading indicator. It'd be a shame if we had to add a skeleton loader just because of the ratings :cry:

**Comment by anasereijo** [comment]
Let's merge this as discussed :D

**Review by spydon — APPROVED** [review]

**Pull request merged**
