### PR TITLE
chore: update flutter, yaru, handy_window

### PR DESCRIPTION
**Pull request by Feichtmeier**
- for yaru yaru test and ubuntu widgets needed an update
- for which flutter  and file needed to be updated
- additionally updated handy_window to align gtk theme with yaru.dart

@BLKKKBVSIK 
looked for the workflow files, but apparently didnt find where you set up the flutter version? in some other repo/script?

### CODE REVIEW

**Review by BLKKKBVSIK — APPROVED** [review]
Awesome!
That's a wonderful QoL improvement to have only `yaru` & `yaru_tests` !

**Comment by BLKKKBVSIK** [comment]
We need to fix the checks before merge tho.

**Comment by Feichtmeier** [comment]
yep I am on it, I think some flutter versions for snap and integration test

**Comment by BLKKKBVSIK** [comment]
Yep. Some of them are in `melos.yaml` & `.tool-versions`

**Comment by Feichtmeier** [comment]
should I also fix this issue?

"dont use context across async gaps"
diff:
grafik

**Comment by BLKKKBVSIK** [comment]
This one is annoying.
I guess let's disable the rule just for this one line, since it's a context used for navigation, and we aren't modifying the context in any way before that.
If you can add a //TODO too, so I can revisit it later on.

**Comment by Feichtmeier** [comment]
okay :) alternatively make the _navigatorKey public and access it this way?

**Pull request merged**
