### PR TITLE
docs: Adding the Flutter Linux prerequisites to CONTRIBUTING.md

### LINKED ISSUE #1460: While runnng project on local system i'm getting "fatal error: 'cairo/cairo.h' file not found" Error
While running project on local system. i'm getting "fatal error: 'cairo/cairo.h' file not found" Error

i'm using flutter 3.10.6 version, fvm 2.4.1 and ubuntu 22.04

help me how i can run your project on locally

image

### PR DESCRIPTION
**Pull request by BLKKKBVSIK**
In this PR:

- Adding a requirement entry to CONTRIBUTING.md.

fix #1460

### CODE REVIEW

**Review by d-loose — COMMENTED** [review]
I think this is misleading - libcairo2-dev is a dependency of libgtk-3-dev, which is a [requirement](https://docs.flutter.dev/get-started/install/linux#linux-prerequisites) to build flutter applications on linux in the first place.

**Comment by BLKKKBVSIK** [comment]
We should redirect directly to this URL then. Going to update my PR.

**Comment by BLKKKBVSIK** [comment]
I also modified the Melos introduction since we have multiples packages in the repo now.

**Review by d-loose — APPROVED** [review]
> We should redirect directly to this URL then. Going to update my PR.

We're already linking to that page in the line above, but that specific section is at the very bottom of that page, so maybe it doesn't hurt to link to it again.

**Pull request merged**
