### PR TITLE
fix: Manage page: Hide cancel button when updates are not in progress.

### PR DESCRIPTION
**Pull request by codinesh**
> One thing to amend is that the cancel button should be hidden until the 'Update all' is trigged, as it can be misleading for the users to have a cancel button without context.

As per the comments form #1536, this PR will hide cancel button when updates are not in progress.

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
@anasereijo Is it possible to add that cancel button with singular updates also? like the `update` button will change to `cancel` button? @codinesh will it be easy/viable?

**Comment by codinesh** [comment]
Yes @soumyaDghosh, it would be easy to change text, but we loos the ability to indicate updates in progress as we show loading indicator on the Update all button

**Comment by Feichtmeier** [comment]
The cancel button overflows
grafik

you could use a wrap instead of a row to prevent this

grafik

return Wrap(
      spacing: 10,
      runSpacing: 10,

but then remove the sizedboxes between

**Comment by codinesh** [comment]
Hello @Feichtmeier, thanks for suggestion to use Wrap. I have made the changes in latest commit, can you please check when feasible

**Comment by BLKKKBVSIK** [comment]
LGTM !

@Feichtmeier your reviews are always welcome tho! 💙

**Review by BLKKKBVSIK — APPROVED** [review]

**Comment by soumyaDghosh** [comment]
The update button looks wiered here

Screenshot from 2024-01-19 21-12-57


@BLKKKBVSIK @anasereijo

**Comment by codinesh** [comment]
> The update button looks wiered here
> 
> Screenshot from 2024-01-19 21-12-57
> 
> @BLKKKBVSIK @anasereijo

Hi @soumyaDghosh, thanks for reporting, I will work on the fix for this.

**Comment by soumyaDghosh** [comment]
@codinesh thanks.. But I have already fixed it 😁.. But thanks again for all of your work on the store.

**Pull request merged**
